<a href="https://colab.research.google.com/github/brunobobadilla06/Practica---Ciencia-de-Datos-I/blob/main/Practica_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Importar Numpy y Pandas
import pandas as pd
import numpy as np

In [2]:
# Creando una serie desde una lista
s_lista = pd.Series([10, 20, 30, 40, 50])
s_lista
#

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [3]:
# Creando una serie con indices propios
s_indices = pd.Series([10, 20, 30, 40, 50], index = ['a', 'b', 'c', 'd', 'e'])
s_indices

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [4]:
# creando series desde un diccionario
s_dict = pd.Series({'a': 10, 'b': 20, 'c': 30, 'd': 40, 'e': 50})
s_dict

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [5]:
# Creado un data frame desde un diccionario de listas
data = {
    'Nombre': ['Juan', 'Ana', 'Pedro', 'Maria'],
    'Edad': [25, 30, 35, 40],
    'Ciudad': ['Madrid', 'Barcelona', 'Valencia', 'Sevilla']
}
df = pd.DataFrame(data)
df

  Nombre  Edad     Ciudad
0   Juan    25     Madrid
1    Ana    30  Barcelona
2  Pedro    35   Valencia
3  Maria    40    Sevilla

In [6]:
# Creando un data frame con indices personalizados
df_indice = pd.DataFrame(data, index = ['a', 'b', 'c', 'd'])
df_indice

  Nombre  Edad     Ciudad
a   Juan    25     Madrid
b    Ana    30  Barcelona
c  Pedro    35   Valencia
d  Maria    40    Sevilla