<a href="https://colab.research.google.com/github/brunobobadilla06/Practica---Ciencia-de-Datos-I/blob/main/Practica_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Introducción a la Estadística Descriptiva con Python y Pandas

En este notebook, daremos nuestros primeros pasos en el análisis de datos utilizando Python y la librería Pandas. La estadística es una herramienta fundamental para cualquier Data Scientist, ya que nos permite comprender, resumir y encontrar patrones en los datos.

Objetivos:

Entender qué es la estadística descriptiva.
Aprender a cargar y explorar datos usando Pandas.
Calcular e interpretar medidas de tendencia central (media, mediana, moda).
Calcular e interpretar medidas de dispersión (rango, varianza, desviación estándar, cuartiles).
Visualizar datos de forma básica para entender su distribución.

Librerías que usaremos:

Pandas: La librería estrella para manipulación y análisis de datos en Python. Proporciona estructuras de datos como los DataFrames, que son como tablas súper poderosas.
NumPy: Fundamental para cálculos numéricos en Python. Pandas se apoya mucho en NumPy.
Matplotlib / Seaborn: Librerías para crear visualizaciones (gráficos) de nuestros datos.

In [1]:
#Importar librerias necesarias
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Establece un tema visual agradable para los graficos seaborn
sns.set_theme(style= "whitegrid")

In [2]:
# Crear un diccionario con los datos de los estudiantes
datos = {
    'Nombre': ['Ana', 'Luis', 'Carlos', 'Sofía', 'Juan', 'Elena', 'Pedro', 'Laura', 'David', 'María'],
    'Edad': [20, 22, 21, 23, 20, 21, 24, 20, 21, 23],
    'Calificacion': [85, 92, 78, 95, 88, 76, 82, 90, 85, 79],
    'Ciudad': ['Madrid', 'Barcelona', 'Madrid', 'Valencia', 'Madrid', 'Barcelona', 'Sevilla', 'Madrid', 'Valencia', 'Sevilla']
}

# Crear un DataFrame de Pandas a partir del diccionario
df_estudiantes = pd.DataFrame(datos)

# Mostrar el DataFrame completo
print("DataFrame de Estudiantes:")
df_estudiantes

DataFrame de Estudiantes:

   Nombre  Edad  Calificacion     Ciudad
0     Ana    20            85     Madrid
1    Luis    22            92  Barcelona
2  Carlos    21            78     Madrid
3   Sofía    23            95   Valencia
4    Juan    20            88     Madrid
5   Elena    21            76  Barcelona
6   Pedro    24            82    Sevilla
7   Laura    20            90     Madrid
8   David    21            85   Valencia
9   María    23            79    Sevilla

2. Exploración Inicial de los Datos

Antes de hacer cálculos complejos, siempre debemos explorar nuestros datos para entender su estructura y contenido. Pandas nos ofrece funciones muy útiles para esto.

.head(n): Muestra las primeras n filas (por defecto 5).
.tail(n): Muestra las últimas n filas (por defecto 5).
.shape: Devuelve una tupla con (número de filas, número de columnas).
.info(): Proporciona un resumen conciso del DataFrame, incluyendo el tipo de dato de cada columna y si hay valores nulos.
.dtypes: Muestra el tipo de dato de cada columna.
.describe(): Calcula estadísticas descriptivas básicas para las columnas numéricas (conteo, media, desviación estándar, mínimo, cuartiles, máximo).

In [3]:
# 1. Mostrar las primeras 5 filas
print("Primeras 5 filas:")
display(df_estudiantes.head())

Primeras 5 filas:

   Nombre  Edad  Calificacion     Ciudad
0     Ana    20            85     Madrid
1    Luis    22            92  Barcelona
2  Carlos    21            78     Madrid
3   Sofía    23            95   Valencia
4    Juan    20            88     Madrid

In [4]:
# 2. Mostrar las últimas 5 filas
print("Últimas 5 filas:")
display(df_estudiantes.tail())

Últimas 5 filas:

  Nombre  Edad  Calificacion     Ciudad
5  Elena    21            76  Barcelona
6  Pedro    24            82    Sevilla
7  Laura    20            90     Madrid
8  David    21            85   Valencia
9  María    23            79    Sevilla

In [5]:
# 3. Mostrar la cantidad de filas y columnas
print("Dimensiones del DataFrame:")
print(df_estudiantes.shape)

print("Cantidad de filas:", df_estudiantes.shape[0])
print("Cantidad de columnas:", df_estudiantes.shape[1])

Dimensiones del DataFrame:
(10, 4)
Cantidad de filas: 10
Cantidad de columnas: 4

In [6]:
# 4. Mostrar información general del DataFrame
print("Información general:")
df_estudiantes.info()

Información general:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Nombre        10 non-null     object
 1   Edad          10 non-null     int64
 2   Calificacion  10 non-null     int64
 3   Ciudad        10 non-null     object
dtypes: int64(2), object(2)
memory usage: 452.0+ bytes

In [7]:
# 5. Mostrar el tipo de dato de cada columna
print("Tipos de datos:")
print(df_estudiantes.dtypes)

Tipos de datos:
Nombre          object
Edad             int64
Calificacion     int64
Ciudad          object
dtype: object

In [8]:
# 6. Mostrar las estadísticas descriptivas de las columnas numéricas
print("Estadísticas descriptivas:")
display(df_estudiantes.describe())

Estadísticas descriptivas:

            Edad  Calificacion
count  10.000000     10.000000
mean   21.500000     85.000000
std     1.433721      6.306963
min    20.000000     76.000000
25%    20.250000     79.750000
50%    21.000000     85.000000
75%    22.750000     89.500000
max    24.000000     95.000000

3. Medidas de Tendencia Central

Estas medidas nos indican alrededor de qué valor se agrupan los datos. Son un “centro” representativo del conjunto de datos.

Media (Mean): El promedio aritmético. Se calcula sumando todos los valores y dividiendo por la cantidad de valores. Es sensible a valores extremos (outliers).
Mediana (Median): El valor que se encuentra justo en el medio cuando los datos están ordenados. Si hay un número par de datos, es el promedio de los dos valores centrales. Es menos sensible a outliers que la media.
Moda (Mode): El valor (o valores) que aparece con mayor frecuencia en el conjunto de datos. Puede haber más de una moda (bimodal, multimodal) o ninguna. Es útil para datos categóricos y numéricos discretos.

Calcularemos estas medidas para las columnas Calificacion y Edad.

In [10]:
#Media
# Seleccionar la columna Calificacion y calcular la media
media_calificacion = df_estudiantes['Calificacion'].mean()
print("Media de Calificacion:", media_calificacion)

# Seleccionar la columna Edad y calcular la media
media_edad = df_estudiantes['Edad'].mean()
print("Media de Edad:", media_edad)

Media de Calificacion: 85.0
Media de Edad: 21.5

In [11]:
# Mediana
# Mediana de columna calificacion y edad
mediana_calificacion = df_estudiantes['Calificacion'].median()
print("Mediana de Calificacion:", mediana_calificacion)

mediana_edad = df_estudiantes['Edad'].median()
print("Mediana de Edad:", mediana_edad)
#

Mediana de Calificacion: 85.0
Mediana de Edad: 21.0

In [13]:
# Moda
# SELECIONAR LA COLUMNA CALIFICACION Y EDAD
moda_calificacion = df_estudiantes['Calificacion'].mode()
print("Moda de Calificacion:", moda_calificacion)

moda_edad = df_estudiantes['Edad'].mode()
print("Moda de Edad:", moda_edad)

# La moda de la ciudad
moda_ciudad = df_estudiantes['Ciudad'].mode()
print("Moda de Ciudad:", moda_ciudad)
#

Moda de Calificacion: 0    85
Name: Calificacion, dtype: int64
Moda de Edad: 0    20
1    21
Name: Edad, dtype: int64
Moda de Ciudad: 0    Madrid
Name: Ciudad, dtype: object

4. Medidas de Dispersión

Estas medidas nos indican qué tan “esparcidos” o “variados” están los datos. No basta con saber el centro, también necesitamos saber si los datos están muy juntos o muy separados.

Rango (Range): La diferencia entre el valor máximo y el valor mínimo. Es fácil de calcular, pero muy sensible a outliers.
Varianza (Variance): Mide la dispersión promedio de los datos alrededor de la media, elevada al cuadrado. Sus unidades están al cuadrado (por ejemplo, puntos al cuadrado), lo que dificulta su interpretación directa.
Desviación estándar (Standard Deviation): Es la raíz cuadrada de la varianza. Mide la dispersión promedio de los datos alrededor de la media, pero en las mismas unidades que los datos originales, lo que la hace más interpretable. Una desviación estándar baja indica que los datos están agrupados cerca de la media; una alta indica que están más dispersos.
Cuartiles (Quartiles): Dividen los datos ordenados en cuatro partes iguales.
Q1 (primer cuartil): El valor por debajo del cual se encuentra el 25 % de los datos.
Q2 (segundo cuartil): La mediana (50 % de los datos por debajo).
Q3 (tercer cuartil): El valor por debajo del cual se encuentra el 75 % de los datos.
Rango intercuartílico (IQR - Interquartile Range): La diferencia entre el tercer cuartil (Q3) y el primer cuartil (Q1). Representa el rango donde se encuentra el 50 % central de los datos y es resistente a outliers.

La función .describe() que vimos antes ya nos da el mínimo, máximo, Q1 (25 %), Q2 (50 % o mediana) y Q3 (75 %).